### PR TITLE
Docker-container

### PR DESCRIPTION
**Pull request by kamilzabielski**
These commits involve in `docker` deployment only.

This patch:
* Adds missing files to `.dockerignore` to make sure that none of not-needed files are deployed.
* Upgrades `docker-compose` up to `3`.
* Adds better documentation to `image` comment in `docker-compose`.
* Adds better port definition.
* Refactorizes Dockerfile.
* Adds proper naming-convention for `docker-entrypoint` deployment.
* Cuts `apache_default` website as it does not add any value.

### CODE REVIEW

**Comment by kamilzabielski** [comment]
@ptrofimov: Ping.
Could you review?

**Comment by pentium10** [comment]
@kamilzabielski I could review but tell me a bit how to create myself the environment, as I am not in Docker yet.

**Comment by kamilzabielski** [comment]
@pentium10 
* Pull the code from my branch. 
* Change directory into the root of clone git-repository.
* Type: `docker-compose up -d`. 
* Open browser. 
* Type: `localhost`

**Comment by kamilzabielski** [comment]
@pentium10 Can I help you with verifying pull-request? Have you got any questions?

**Comment by pentium10** [comment]
cool, honestly this was my first time that I ran a docker project and it was awesome experience

**Comment by pentium10** [comment]
how would a docker-image would help this project? I am novice to docker.

**Comment by kamilzabielski** [comment]
@pentium10 Well, actually, it will allow users to easily run `beanstalkd-console` project without installing it's dependencies locally, typing simply `docker run -e BEANSTALKD=beanstalkd.com beastalkd-console`. Without `php` or any dependency. Ignoring platform or operating system underneath.

**Pull request merged**
